version: "3.0"
services:
  frontend:
    image: backend:latest
    build: ./backend
    container_name: backend
    ports:
      - 6080:80
  frontend:
    image: frontend:latest
    build: ./frontend
    container_name: frontend
    ports:
      - 5080:80